You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"



class Solution {
public:
    char findTheDifference(string s, string t) {
        int count[26] = {0};
        
        for (char c : s) {
            count[c - 'a']++;
        }
        
       
        for (char c : t) {
            count[c - 'a']--;
        }
        
        
        for (int i = 0; i < 26; i++) {
            if (count[i] == -1) {
                return 'a' + i;
            }
        }
     return'\0';
    }
};


/*
1->Create an array for storing count.
2->Using foreach loop asignn chars of string 's' in count and in position increment value by 1.
3->Now by string 't' decrement the value of available chars to 0.
4->using a for loop set upto 26 check that any count[i] is equal to 1.
5->Return the missing char

Time Complexity: O(n + m)

Space Complexity: O(1)

*/
